version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pasSworD
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pasSworD
      ME_CONFIG_MONGODB_URL: mongodb://root:pasSworD@mongo:27017/
    ports:
      - 8081:8081
